language: node_js
node_js:
  - "12.16.2"

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules

  install:
    - npm install -g serverless
    - npm install
    - npm install wait-on

  script:
    - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID_DEVELOPMENT} --secret ${AWS_SECRET_ACCESS_KEY_DEVELOPMENT} --profile serverless-user -o
    # - serverless offline start && wait-on http://localhost:3000 &
    - npm run lint
    # - sls test
    - npm run test:unit
    # - npm run test:int
    - serverless deploy -s ${STAGE_NAME} --aws-profile serverless-user
    # - kill $(jobs -p) || true

environments:
  # - &PRODUCTION_ENV
  #   - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PRODUCTION}
  #   - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PRODUCTION}

  - &DEVELOPMENT_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEVELOPMENT}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}
    - SERVERLESS_ACCESS_KEY=${SERVERLESS_ACCESS_KEY}

jobs:
  include:
    # master deploys to 'dev', however, in future, master will deploy to 'prod'
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Dev API"
      if: type = push AND NOT branch = master
      env:
        - STAGE_NAME=${TRAVIS_BRANCH}
        - *DEVELOPMENT_ENV
    # TODO: in future master will deploy to 'prod'
    # - <<: *DEPLOY_SERVICE_JOB
    #   name: "Production Deploy API"
    #   if: type = push AND branch = master
    #   env:
    #     - STAGE_NAME=${TRAVIS_BRANCH}
    #     - *PRODUCTION_ENV
