service:
  name: branch-api
  app: branch
  org: nicholaspretorius

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  profiles:
    dev: serverless-user
  # prod: serverless-prod

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  profile: ${self:custom.profiles.${self:provider.stage}}
  cfnRole: arn:aws:iam::839211811792:role/branch-api-dev-eu-west-1-lambdaRole
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  ping:
    handler: src/ping.main
    events:
      - http:
          method: get
          path: ping
